#!/bin/bash

sed -i \
    -e 's:- through-the-pages$:- листая-страницы:g' \
    -e 's:"through-the-pages":"листая-страницы":g' \
    -e 's:- mood$:- настроение:g' \
    -e 's:"mood":"настроение":g' \
    -e 's:- gedanken$:- мысли:g' \
    -e 's:"gedanken":"мысли":g' \
    -e 's:- doch$:- однако:g' \
    -e 's:"doch":"однако":g' \
    -e 's:- cognitive$:- познавательно:g' \
    -e 's:"cognitive":"познавательно":g' \
    -e 's:- through-the-window$:- за-окном:g' \
    -e 's:"through-the-window":"за-окном":g' \
    -e 's:- occasion$:- события:g' \
    -e 's:"occasion":"события":g' \
    -e 's:- музыкой навеяло$:- музыкой-навеяло:g' \
    -e 's:- sci fiction$:- sci-fiction:g' \
    -e 's:- жизнь в науке$:- жизнь-в-науке:g' \
    *.md
