#!/bin/bash

sed -i \
    -e 's:- листая страницы$:- through-the-pages:g' \
    -e 's:- сисадмин$:- sysadmin:g' \
    -e 's:- люди науки$:- science-people:g' \
    -e 's:- lj$:- blogging:g' \
    -e 's:- наука$:- science:g' \
    -e 's:- история$:- history:g' \
    -e 's:- микроистория$:- microhistory:g' \
    -e 's:- культура$:- culture:g' \
    -e 's:- история науки$:- science-history:g' \
    -e 's:- философия науки$:- science-philosophy:g' \
    -e 's:- образование$:- education:g' \
    -e 's:- настроение$:- mood:g' \
    -e 's:- мысли$:- gedanken:g' \
    -e 's:- однако$:- doch:g' \
    -e 's:- познавательно$:- cognitive:g' \
    -e 's:- физика$:- physics:g' \
    -e 's:- за окном$:- through-the-window:g' \
    -e 's:- события$:- occasion:g' \
    -e 's:- научпоп$:- popular-science:g' \
    -e 's:- программирование$:- programming:g' \
    -e 's:- литературоведение$:- literary-studies:g' \
    -e 's:- политика$:- politics:g' \
    *.md
