#!/bin/bash

sed -i \
    -e 's:- листая страницы$:- through-the-pages:g' \
    -e 's:- люди науки$:- science-people:g' \
    -e 's:- lj$:- blogging:g' \
    -e 's:- наука$:- science:g' \
    -e 's:- история$:- history:g' \
    *.md
