#!/bin/bash

sed -i \
    -e "s|http://gen.lib.rus.ec|http://libgen.is|g" \
    -e "s|http://libgen.io|http://libgen.is|g" \
    -e "s|http://libgen.is|http://libgen.rs|g" \
    -e "s|https://libgen.is|http://libgen.rs|g" \
    -e "s|http://flibusta.net|http://flibusta.is|g" \
    -e "s|http://libgen.rs|http://libgen.li|g" \
    *.md
